jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP7/TNOVA_D7.2_Integrated_Pilot_and_Validation_Report_v1.0.pdf" -D title="D7.2 Integrated Pilot and Validation Report " -D year="2017" > "./WP7/TNOVA_D7.2_Integrated_Pilot_and_Validation_Report_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP7/TNOVA_D7.1_Early_Pilot_Site_Deployment_v1.0.pdf" -D title="D7.1 Early Pilot Site Deployment " -D year="2016" > "./WP7/TNOVA_D7.1_Early_Pilot_Site_Deployment_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP7/TNOVA D7.3 Overall Assessment and Roadmap_v1.0.pdf" -D title="./WP7/TNOVA D7.3 Overall Assessment and Roadmap .pdf" -D year="2017" > "./WP7/TNOVA D7.3 Overall Assessment and Roadmap_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.42.pdf" -D title="D4.42" -D year="2017" > "./WP4/TNOVA_D4.42.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.41_Monitoring_and_Maintenance_Interim.pdf" -D title="D4.41 Monitoring and Maintenance Interim" -D year="2016" > "./WP4/TNOVA_D4.41_Monitoring_and_Maintenance_Interim.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.51_Infrastructure_Integration_and_Deployment-Interim_v1.0.pdf" -D title="D4.51 Infrastructure Integration and Deployment-Interim " -D year="2017" > "./WP4/TNOVA_D4.51_Infrastructure_Integration_and_Deployment-Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.32_SDK for SDN - Final_v1.0.pdf" -D title="D4.32 SDK for SDN - Final " -D year="2017" > "./WP4/TNOVA_D4.32_SDK for SDN - Final_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.01_Interim Report on Infrastructure Virtualisation and Management_v1.0.pdf" -D title="D4.01 Interim Report on Infrastructure Virtualisation and Management " -D year="2015" > "./WP4/TNOVA_D4.01_Interim Report on Infrastructure Virtualisation and Management_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.21_SDN_Control_Plane_Interim.pdf" -D title="D4.21 SDN Control Plane Interim" -D year="2015" > "./WP4/TNOVA_D4.21_SDN_Control_Plane_Interim.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.31_SDK for SDN - Interim_v1.0.pdf" -D title="D4.31 SDK for SDN - Interim " -D year="2017" > "./WP4/TNOVA_D4.31_SDK for SDN - Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.1_Infrastructure_Virtualisation_v1.0.pdf" -D title="D4.1 Infrastructure Virtualisation " -D year="2017" > "./WP4/TNOVA_D4.1_Infrastructure_Virtualisation_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP4/TNOVA_D4.22_SDN_Control_Plane_Final.pdf" -D title="D4.22 SDN Control Plane Final" -D year="2017" > "./WP4/TNOVA_D4.22_SDN_Control_Plane_Final.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP6/TNOVA_D6.1_Service_Description_Framework_v1.0.pdf" -D title="D6.1 Service Description Framework " -D year="2016" > "./WP6/TNOVA_D6.1_Service_Description_Framework_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP6/TNOVA_D6.01_Interim Report on marketplace implementation_v1.0.pdf" -D title="D6.01 Interim Report on marketplace implementation " -D year="2015" > "./WP6/TNOVA_D6.01_Interim Report on marketplace implementation_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP6/TNOVA_D6.2_Brokerage_Module_v1.0.pdf" -D title="D6.2 Brokerage Module " -D year="2017" > "./WP6/TNOVA_D6.2_Brokerage_Module_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP6/TNOVA_D6.4_SLAs_and_billing_v1.0.pdf" -D title="D6.4 SLAs and billing " -D year="2016" > "./WP6/TNOVA_D6.4_SLAs_and_billing_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP6/TNOVA_D6.3_Users_Dashboard_v1.0.pdf" -D title="D6.3 Users Dashboard " -D year="2017" > "./WP6/TNOVA_D6.3_Users_Dashboard_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP5/TNOVA_D5.01_Interim Report on Network Functions and associated framework_v1.0.pdf" -D title="D5.01 Interim Report on Network Functions and associated framework " -D year="2015" > "./WP5/TNOVA_D5.01_Interim Report on Network Functions and associated framework_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP5/TNOVA_D5_2.pdf" -D title="D5 2" -D year="2017" > "./WP5/TNOVA_D5_2.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP5/TNOVA_D5.31 - Network Functions Implementation and Testing - Interim_v1.0.pdf" -D title="D5.31 - Network Functions Implementation and Testing - Interim " -D year="2016" > "./WP5/TNOVA_D5.31 - Network Functions Implementation and Testing - Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP5/TNOVA_D5_1_Network_Function_Store_v1.0.pdf" -D title="D5 1 Network Function Store " -D year="2016" > "./WP5/TNOVA_D5_1_Network_Function_Store_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.51_Planning of Trials and Evaluation-Interim_v1.0.pdf" -D title="D2.51 Planning of Trials and Evaluation-Interim " -D year="2015" > "./WP2/TNOVA_D2.51_Planning of Trials and Evaluation-Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.21_Overall System Architecture and Interfaces_v.1.0.pdf" -D title="D2.21 Overall System Architecture and Interfaces v.1.0" -D year="2014" > "./WP2/TNOVA_D2.21_Overall System Architecture and Interfaces_v.1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.52_Planning_of_Trials_and_Evaluation-Final_v1.0.pdf" -D title="D2.52 Planning of Trials and Evaluation-Final " -D year="2015" > "./WP2/TNOVA_D2.52_Planning_of_Trials_and_Evaluation-Final_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.1_System Use Cases and Requirements_v1.0.pdf" -D title="D2.1 System Use Cases and Requirements " -D year="2015" > "./WP2/TNOVA_D2.1_System Use Cases and Requirements_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.42_Specification_of_the_Network_Function_Framework_and_T-NOVA_Marketplace.pdf" -D title="D2.42 Specification of the Network Function Framework and T-NOVA Marketplace" -D year="2016" > "./WP2/TNOVA_D2.42_Specification_of_the_Network_Function_Framework_and_T-NOVA_Marketplace.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.41_Specification of the Network Function Framework and T-NOVA Marketplace - Interim_v1.0.pdf" -D title="D2.41 Specification of the Network Function Framework and T-NOVA Marketplace - Interim " -D year="2014" > "./WP2/TNOVA_D2.41_Specification of the Network Function Framework and T-NOVA Marketplace - Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.32 -_Specification of the Infrastructure Virtualisation, Management and Orchestration_v1.0.pdf" -D title="D2.32 - Specification of the Infrastructure Virtualisation, Management and Orchestration " -D year="2016" > "./WP2/TNOVA_D2.32 -_Specification of the Infrastructure Virtualisation, Management and Orchestration_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.31_Specification of the Infrastructure Virtualisation, Management and Orchestration - Interim_v1.0.pdf" -D title="D2.31 Specification of the Infrastructure Virtualisation, Management and Orchestration - Interim " -D year="2014" > "./WP2/TNOVA_D2.31_Specification of the Infrastructure Virtualisation, Management and Orchestration - Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP2/TNOVA_D2.22_Overall_System_Architecture_and_Interfaces_v1.0.pdf" -D title="D2.22 Overall System Architecture and Interfaces " -D year="2015" > "./WP2/TNOVA_D2.22_Overall_System_Architecture_and_Interfaces_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP1/TNOVA_D1.4_Final_Report_v.1.0.pdf" -D title="D1.4 Final Report v.1.0" -D year="2017" > "./WP1/TNOVA_D1.4_Final_Report_v.1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP8/TNOVA_D8.11_Market Assesment_v1.0.pdf" -D title="D8.11 Market Assesment " -D year="2014" > "./WP8/TNOVA_D8.11_Market Assesment_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP8/TNOVA_D8.31-First Report on Dissemination and Communication Activities_v1.0.pdf" -D title="D8.31-First Report on Dissemination and Communication Activities " -D year="2015" > "./WP8/TNOVA_D8.31-First Report on Dissemination and Communication Activities_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP8/TNOVA_D8.21_Interim_Report_on_Standardisation_Activities_v1.0.pdf" -D title="D8.21 Interim Report on Standardisation Activities " -D year="2016" > "./WP8/TNOVA_D8.21_Interim_Report_on_Standardisation_Activities_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP8/TNOVA_D8.32-Dissemination_and_Communication_Activities_v1.0.pdf" -D title="D8.32-Dissemination and Communication Activities " -D year="2017" > "./WP8/TNOVA_D8.32-Dissemination_and_Communication_Activities_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP8/TNOVA_D8.12-Interim_Market_and_Exploitation_Planning_and_Recommendationsv1.0.pdf" -D title="D8.12-Interim Market and Exploitation Planning and Recommendations" -D year="2016" > "./WP8/TNOVA_D8.12-Interim_Market_and_Exploitation_Planning_and_Recommendationsv1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP3/TNOVA_D3.41_ServiceProvisioning_Management_and_Monitoring_Interim_v1.0.pdf" -D title="D3.41 ServiceProvisioning Management and Monitoring Interim " -D year="2017" > "./WP3/TNOVA_D3.41_ServiceProvisioning_Management_and_Monitoring_Interim_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP3/TNOVA_D3.1_Orchestrator_Interfaces_v1.0.pdf" -D title="D3.1 Orchestrator Interfaces " -D year="2016" > "./WP3/TNOVA_D3.1_Orchestrator_Interfaces_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP3/TNOVA_D3.2_Infrastructure_Resource_Repository_v1.0.pdf" -D title="D3.2 Infrastructure Resource Repository " -D year="2015" > "./WP3/TNOVA_D3.2_Infrastructure_Resource_Repository_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP3/TNOVA_D3.01_Interim_Report_on_Orchestrator_Platform_Implementation_v1.0.pdf" -D title="D3.01 Interim Report on Orchestrator Platform Implementation " -D year="2015" > "./WP3/TNOVA_D3.01_Interim_Report_on_Orchestrator_Platform_Implementation_v1.0.pdf.tex"
echo "cool" 
jinja2  ~/bib.tex.tpl -D name="T_NOVA_./WP3/TNOVA_D3.3_Service_Mapping_v1.0.pdf" -D title="D3.3 Service Mapping " -D year="2016" > "./WP3/TNOVA_D3.3_Service_Mapping_v1.0.pdf.tex"
